### ISSUE TITLE
[Gutenberg] Build a hero block for homepage

### ISSUE THREAD

**Issue by postphotos** [xwp/wp-travel-theme#14]
**As an user of the Travel theme, I should have a way to manage the Hero block on the homepage.**

AC1: Hero block should consist of:
-  h1 and h2 subheading
- Search input
- datepicker
- button

Based on @miina and @DavidCramer 's discovery in #9. Related to #12.

**Comment by kienstra** [comment]
**Request For Testing**

Hi Claudio,
Could you please test this block?

1. [Create a new page](http://dev-amp-start-travel.pantheonsite.io/wp-admin/post-new.php?post_type=page)
2. Add a "Hero" block

Expected:
* It matches the [design](https://www.figma.com/file/L14jTE7iNGOE7DH57Ro7ncyu/Travel-Theme?node-id=1%3A9) for desktop and mobile
* It's responsive in the editor and the front-end
* The text here is editable:
<img width="1436" alt="text-editable" src="https://user-images.githubusercontent.com/4063887/39386982-b441ea2c-4a3c-11e8-9f17-ab893c1961d7.png">

**Comment by csossi** [comment]
verified in QA for all browsers except for IE11:
![image](https://user-images.githubusercontent.com/16945664/39728997-969062f4-5227-11e8-8651-5a30198aa188.png)

**Comment by kienstra** [comment]
**IE 11 Support**

Hi @csossi,
Thanks for testing this with IE11, as I asked. Given that AMP [doesn't pledge support of Internet Explorer](https://www.ampproject.org/support/faqs/supported-browsers), I'm going to move this to "Done."
