### ISSUE TITLE
Set up Pantheon environment for the Travel WP theme

### ISSUE THREAD

**Issue by postphotos** [xwp/wp-travel-theme#2]
Not sure if this should go to @ThierryA or @westonruter.

**Comment by kienstra** [comment]
*Closed*

Thanks to @westonruter for setting up the environment for this theme:
https://dev-amp-start-travel.pantheonsite.io/

**Comment by westonruter** [comment]
The environment is created but it is not set up yet.

**Comment by westonruter** [comment]
Fixed now by https://github.com/xwp/travel/pull/40
