### ISSUE TITLE
[Gutenberg] Build a "Discover" block for Homepage

### ISSUE THREAD

**Issue by postphotos** [xwp/wp-travel-theme#20]
part of the components listed in #12.
The discover / display post block.

As requested (and detailed) by @miina here.

Mockups are available here:
- https://www.figma.com/file/L14jTE7iNGOE7DH57Ro7ncyu/Travel-Theme
- https://ampstart-iframes.firebaseapp.com/templates/travel/travel.amp

**Comment by kienstra** [comment]
**Moving To "QA" Column**

Merged PR #13 [added a "Discover" block](https://github.com/xwp/travel/pull/13/files#diff-3215f011460155a7b0e289ca288c19ecR8).

**Comment by miina** [comment]
Hi @kienstra, with this block it's the same as with Featured destinations: what #13 included was displaying static block, however, this ticket is for adding pulling the content dynamically and is still review-iterations stage (#19).

**Comment by kienstra** [comment]
**Request For Testing**

Hi Claudio,
Could you please test this block?

1. [Create a new page](http://dev-amp-start-travel.pantheonsite.io/wp-admin/post-new.php?post_type=page)
2. Add a "Discover" block

Expected:
* It matches the [design](https://www.figma.com/file/L14jTE7iNGOE7DH57Ro7ncyu/Travel-Theme?node-id=1%3A9) 
* It displays well on desktop and mobile
* The text here is editable:

<img width="1431" alt="editable-discover" src="https://user-images.githubusercontent.com/4063887/39390048-fba8c6fc-4a54-11e8-9d6c-e05c90f2bc7b.png">

**Comment by csossi** [comment]
The only QA comment here is perhaps making the default colour of the subheading darker - much too  hard to read on an image background:
![image](https://user-images.githubusercontent.com/16945664/39678400-16324b40-515a-11e8-873c-338716570503.png)

**Comment by kienstra** [comment]
**Context Of Block**

Hi @csossi,
That's a good point. I should have added that we only expect this block on the [homepage](http://dev-amp-start-travel.pantheonsite.io/), where the background of the block will be white.
