### ISSUE TITLE
[Gutenberg] Build a "Secondary Header" block for Homepage

### ISSUE THREAD

**Issue by postphotos** [xwp/wp-travel-theme#21]
part of the components listed in #12.
Consists of h2 and div subheading.

As requested (and detailed) by @miina here.

Mockups are available here:
- https://www.figma.com/file/L14jTE7iNGOE7DH57Ro7ncyu/Travel-Theme
- https://ampstart-iframes.firebaseapp.com/templates/travel/travel.amp

**Comment by miina** [comment]
@postphotos Looks like this block would also be part of #20 (that's the section where the notes say "Latest blog post, regular post type" in https://www.figma.com/file/L14jTE7iNGOE7DH57Ro7ncyu/Travel-Theme).

**Comment by postphotos** [comment]
Closed, duplicate #19, #20.
