### ISSUE TITLE
[Gutenberg] Build a "From the blog" block for Homepage

### ISSUE THREAD

**Issue by postphotos** [xwp/wp-travel-theme#22]
part of the components listed in #12.
Pulls most recent published post.

As requested (and detailed) by @miina here.

Mockups are available here:
- https://www.figma.com/file/L14jTE7iNGOE7DH57Ro7ncyu/Travel-Theme
- https://ampstart-iframes.firebaseapp.com/templates/travel/travel.amp

**Comment by miina** [comment]
@postphotos One note: this block would be initially implemented as part of the "Discover" block (#20).

**Comment by postphotos** [comment]
Closed, duplicate #19, #20.
