### ISSUE TITLE
[Gutenberg] Build a "Top adventures" block for Homepage

### ISSUE THREAD

**Issue by postphotos** [xwp/wp-travel-theme#23]
part of the components listed in #12.

As requested (and detailed) by @miina here.

Mockups are available here:

- https://www.figma.com/file/L14jTE7iNGOE7DH57Ro7ncyu/Travel-Theme
- https://ampstart-iframes.firebaseapp.com/templates/travel/travel.amp

Some notes from #9 apply here:
> Would be used for the display post (next to "Discover Adventures"), for Top Adventures Near You;
> Would have controls to choose:
> How many posts to show;
> Which category posts to show;
> How to sort (e.g. by meta value X);
> Layout / or which fields to display.
> For example for the post next to "Discover Adventures" you could choose layout A; 1 post; category "Food", for the the Top Adventures Near You" could choose layout B; 3 posts; category "Adventure"; sort by meta value Review;
> Question: Does this make sense for these two sections from the editor's point of view?
> 
> Category/taxonomy list block:
> Would be used for "Browse by activity" and "Featured destinations";
> Would have option to choose which fields to display (e.g. meta value such as icon / background image; count of posts
> Option to choose how many categories to display;
> Perhaps option to filter by "featured"
> Option to sort by ... ?
>

**Comment by kienstra** [comment]
**Request For Testing**

Hi Claudio,
Could you please test this block?

1. [Create a new page](http://dev-amp-start-travel.pantheonsite.io/wp-admin/post-new.php?post_type=page)
2. Add a "Popular Adventures" block

<img width="1432" alt="popular-adventures-block" src="https://user-images.githubusercontent.com/4063887/39386459-507540cc-4a3a-11e8-840d-2b15fd194689.png">

Expected:
* It matches the [design](https://www.figma.com/file/L14jTE7iNGOE7DH57Ro7ncyu/Travel-Theme?node-id=1%3A9) for desktop and mobile
* It's responsive in the editor and the front-end
* The heading is editable:
<img width="1429" alt="popular-adventures" src="https://user-images.githubusercontent.com/4063887/39386525-ac384e5e-4a3a-11e8-8804-d289c3ce31fd.png">

**Comment by csossi** [comment]
Verified in QA:
Win10 - Edge, Chrome, FFox
MacOSX - Safari, Chrome
iOS11.3 - Safari, Chrome
Android7.0 - Chrome
