### ISSUE TITLE
[Gutenberg] Build a second search block for Homepage

### ISSUE THREAD

**Issue by postphotos** [xwp/wp-travel-theme#26]
part of the components listed in #12.

As requested (and detailed) by @miina here.

Mockups are available here:

- https://www.figma.com/file/L14jTE7iNGOE7DH57Ro7ncyu/Travel-Theme
- https://ampstart-iframes.firebaseapp.com/templates/travel/travel.amp

**Comment by kienstra** [comment]
**Request For Testing**

Hi Claudio,
Could you please test this block?

1. [Create a new page](http://dev-amp-start-travel.pantheonsite.io/wp-admin/post-new.php?post_type=page)
2. Add a "Search" block

Expected:
* It matches the [design](https://www.figma.com/file/L14jTE7iNGOE7DH57Ro7ncyu/Travel-Theme?node-id=1%3A9) 
* The text here is editable:

<img width="1432" alt="search-block-text" src="https://user-images.githubusercontent.com/4063887/39390012-46d5e610-4a54-11e8-9287-740ff85c3b7e.png">

**Comment by csossi** [comment]
Added a search block to post at http://dev-amp-start-travel.pantheonsite.io/wp-admin/post.php?post=202&action=edit. Published, but am not seeing it on Site

**Comment by kienstra** [comment]
Hi @csossi,
The block looks to appear on the [front-end of that URL](http://dev-amp-start-travel.pantheonsite.io/?page_id=202&preview=true) now, but one of the 'Search' blocks shows this error in the editor:

>This block has encountered an error and cannot be previewed.

Does it also appear on the front-end for you?
