### ISSUE TITLE
Extend "adventure" custom post type with custom taxonomies

### ISSUE THREAD

**Issue by postphotos** [xwp/wp-travel-theme#27]
**To power filtering and searching, we need taxonomies for Activities and Locations.**

Related to #10.

**Comment by miina** [comment]
Note that `Adventure` taxonomy has been already added (to some extent) in #30 via `amp_travel_register_taxonomies` in `functions.php`:
https://github.com/xwp/travel/blob/feature/24-activity_list_block/functions.php#L137-L170

**Comment by kienstra** [comment]
**Moving To "Ready For Merging" Column**

Merged PR #31 adds taxonomies. So I'm moving this issue to "Ready For Merging." 

The pages for the taxonomies could probably use QA. But I don't think this issue needs traditional QA.
