### ISSUE TITLE
Create a default footer.php file

### ISSUE THREAD

**Issue by postphotos** [xwp/wp-travel-theme#44]
**As a page template, I should call a theme-wide `footer.php` file instead of using my own declarations for footer.**
AC1: Each page template should call `footer.php`.
AC2: Any legacy items that `footer.php` already controls should be removed from page templates.

**Comment by kienstra** [comment]
**Question About Dynamic Data**

There is a [footer.php](https://github.com/xwp/travel/blob/0afa37182211f4ee96d74697bc76a7b9cc279b00/footer.php) now, but, it's static. For example, the "Company" and "Discover" links on the [dev site](http://dev-amp-start-travel.pantheonsite.io/) are static, and the email submission form doesn't work.

Does the footer need dynamic data?
