### ISSUE TITLE
[Gutenberg] Integrate the ‘Travel Angles’ block into the ‘Hero’ block, update editor display

### ISSUE THREAD

**Issue by postphotos** [xwp/wp-travel-theme#50]
**[Gutenberg] As a visitor, I should have the “Travel angles” block inside the “Hero” block with a matched editor and front-end experience.**
AC1. Move the ‘Travel Angles’ block into the ‘Hero’ block.
AC2. Make that block full-width in the editor. For an example of that, add a (native) image block, and set it to ‘Full width.’
AC3. Make the block in the editor look more similar to the front-end. For example, in the editor, display an image in the background like the display on the front-end.
AC4. The ability to select the image in the editor is a “nice to have,” but not required. It can remain a static image, if need be.

Related #12. (See mockups and other general layout notes there.)
See these in deployment here: http://dev-amp-start-travel.pantheonsite.io/

_As requested by @kienstra_

**Comment by postphotos** [comment]
@kienstra asks: @miina: would you be available for this?

**Comment by kienstra** [comment]
This was applied in PR #54.
