### ISSUE TITLE
Add dynamic menus in footer.php

### ISSUE THREAD

**Issue by postphotos** [xwp/wp-travel-theme#58]
**As a site admin, I should have an easy way to manage the links in the footer.**
AC1: Allow for a site admin to edit these two menu areas using the WP menu features.
AC2: Replace the current hardcoded markup with a standard menu (`walker` etc.) so that a user could manage the sections without needing to edit the theme directly.

Likely low priority but also pretty straightforward, but the current listing is hardco

_as reported by @kienstra_

**Comment by kienstra** [comment]
**Request For Testing**

Hi Claudio,
Could you please test this? Please ensure the menu [shown here](https://github.com/xwp/travel/pull/64#issuecomment-383709525) appears in the footer of pages, including the [homepage](http://dev-amp-start-travel.pantheonsite.io/)
