### ISSUE TITLE
Update headings in search and taxonomy listings based on new design

### ISSUE THREAD

**Issue by postphotos** [xwp/wp-travel-theme#59]
**As a user of the Travel theme, when I search or visit a page, have context to what kind of page I'm on, what I just did and how to get back to where I just was.**

This is a placeholder ticket to implement design. Currently, Maxim to update Figma mocks with input from @jwold: https://www.figma.com/file/L14jTE7iNGOE7DH57Ro7ncyu/Travel-Theme

Whatever changes will happen will be added here.

Currently blocked by this design ticket: https://xwp-co.atlassian.net/browse/AP2-40
I'll update the status of this issue with the appropriate ACs when AP2-40 is complete.

**Comment by postphotos** [comment]
related to #37.

**Comment by kienstra** [comment]
**Request To Apply Designs**

Hi @miina,
Thanks for your work on the `search.php` and `archive.php` templates. Could you please apply the newly-updated designs for those?

https://www.figma.com/file/L14jTE7iNGOE7DH57Ro7ncyu/Travel-Theme
