### ISSUE TITLE
Create a bootstrapped (WordPress-VIP style) code area so that certain features can be pulled into a plugin if necessary.

### ISSUE THREAD

**Issue by postphotos** [xwp/wp-travel-theme#6]

**Comment by kienstra** [comment]
**Applied, Moving To "Ready For Merging"**

Hi @postphotos,
With @miina's addition of the [includes/](https://github.com/xwp/travel/tree/c361a86f552dcf58881f986a47a089c004d7ebf1/includes) directory for classes in #13, this requirement is fulfilled. I'm moving this into "Ready For Merging," as it doesn't need traditional QA.
