### ISSUE TITLE
Declare and set up a custom post type for adventure travel results

### ISSUE THREAD

**Issue by postphotos** [xwp/wp-travel-theme#7]
**As an editor or author of a site running the Travel theme, I should have a way to built custom content for "adventure" travel results.**
AC1. A custom post type should be declared.
AC2. Some basic output (`the_title`, `the_content`, etc. or just whatever's inside `single`) should be built so that single views work for this post type.

**Comment by miina** [comment]
@postphotos 
Quick question to clarify:
Would this ticket be about the custom template for the search results page?
Or is this for the custom post type "Adventure" that would be displayed on the "travel results" page?

**Comment by postphotos** [comment]
Hi @miina, The word build here was vague - sorry for the confusion! Not sure how we'll handle search or taxonomic listings yet, but I've updated the title of the ticket and added a formal story and AC inside the description here.

A further set of issues will outline blocks for this page so we can allow for parallel completion of tasks here.

Whether that is declared as `adventure` or `travel-results` I don't really care either way. Adventure sounds like more fun!

**Comment by miina** [comment]
Some details about `adventure` fields:
- needs to have a start date and end date;
- Needs to have a price;
- Needs to have a rating (probably that's not manually editable but maybe would need registering to show up in REST?);

@postphotos Are there any additional fields that I forgot about?

cc @DavidCramer
