### ISSUE TITLE
[Gutenberg] Use dynamic images in the carousel at the top of the single "adventure" page

### ISSUE THREAD

**Issue by postphotos** [xwp/wp-travel-theme#73]
**As an content author working on adventure posts, I want an easy way to manage images that display in the carousel of the single "adventure" page.**

- [x] AC1. Please allow setting the images that appear in the single ‘adventure’ page carousel, via the Gutenberg editor. For example, https://dev-amp-start-travel.pantheonsite.io/adventure/surfing-day-board-and-wetsuits-included-in-price/
- [x] AC2. Featured image should still probably be managed by this component.

_(as reported by @kienstra)_

**Comment by kienstra** [comment]
**Possible Solution**

Hi @miina,
What do you think about this approach to making the carousel images dynamic?

* The 'featured image' for each adventure is the first image in the carousel. If there are no images added below, it's the only one.
* We add an ‘Additional Carousel Images’ section at the bottom of the 'Extended Settings' section that would allow adding more images to the carousel.
* This might use a gallery UI.
* This carousel might have worked well as a block, but it needs to appear above the title. 
<img width="1431" alt="single-adventure-carousel" src="https://user-images.githubusercontent.com/4063887/39386018-3c74d4fe-4a38-11e8-8cda-19a171192d5e.png">

**Comment by kienstra** [comment]
Hi @miina,
Feel free to work on this if you'd like. Otherwise, I will 😄

**Comment by DavidCramer** [comment]
@kienstra @miina I don't mind woking on this 😄 if nobody objects.

**Comment by miina** [comment]
@DavidCramer No objections from me, go for it!

**Comment by kienstra** [comment]
Sounds good, @DavidCramer!

**Comment by kienstra** [comment]
**Deployed, UI As Shown In Description**

Hi @ThierryA,
@DavidCramer's PR for this, #73, is now deployed to the [dev site](https://dev-amp-start-travel.pantheonsite.io/adventure/surfing-day-board-and-wetsuits-included-in-price/). Though I haven't yet added the additional images for the carousel in the editor.

The UI is as shown in the description.

**Comment by ThierryA** [comment]
Awesome, thanks @kienstra
